// Sample seed data for development
export const sampleIdeas = [
  {
    id: '1',
    title: 'AI-Powered Code Review Assistant',
    slug: 'ai-powered-code-review-assistant',
    description: 'Automated code review tool that uses AI to identify bugs, security vulnerabilities, and suggest improvements. Integrates with GitHub, GitLab, and Bitbucket.',
    status: 'APPROVED',
    category: 'Developer Tools',
    marketType: 'B2B SaaS',
    targetAudience: 'Software development teams and tech companies',
    upvoteCount: 342,
    viewCount: 5420,
    userId: '1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    title: 'Personalized Meal Prep Marketplace',
    slug: 'personalized-meal-prep-marketplace',
    description: 'Connect busy professionals with local chefs who create customized weekly meal plans based on dietary restrictions, preferences, and health goals.',
    status: 'APPROVED',
    category: 'Food & Beverage',
    marketType: 'Marketplace',
    targetAudience: 'Health-conscious professionals aged 25-45',
    upvoteCount: 289,
    viewCount: 3850,
    userId: '1',
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: '3',
    title: 'Remote Team Building Platform',
    slug: 'remote-team-building-platform',
    description: 'Virtual activities and games designed specifically for remote teams to improve engagement, culture, and collaboration. Includes icebreakers, challenges, and team events.',
    status: 'APPROVED',
    category: 'HR Tech',
    marketType: 'B2B SaaS',
    targetAudience: 'Remote-first companies and HR departments',
    upvoteCount: 215,
    viewCount: 2940,
    userId: '1',
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
  },
]

export const sampleUser = {
  id: '1',
  name: 'Alex Johnson',
  email: 'alex@example.com',
  emailVerified: null,
  image: null,
  username: 'alexj',
  role: 'USER',
  createdAt: new Date(),
  updatedAt: new Date(),
}
